server:
  port:
    8763 

spring:
  cloud:
    stream:
      bindings:
        input:
          contentType: application/xml
          destination: biller_config
        kafka:
          binder:
            brokers: localhost:9092
            zkNodes: localhost:2181
