server:
  port:
    8764

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    stream:
      bindings:
        input:
          contentType: application/json
          destination: biller_config
        kafka:
          binder:
            brokers: localhost:9092
            zkNodes: localhost:2181

beanio:
  xmlfile: C:\tmp\tmp\mapping_biller.xml

biller:
  request: biller2_request
  response: biller2_response
