server:
  port:
    8763

spring:
  cloud:
    stream:
      bindings:
        input:
          contentType: application/json
          destination: biller_config
        kafka:
          binder:
            brokers: localhost:9092
            zkNodes: localhost:2181

beanio:
  xmlfile: C:\Users\w.rattanasamoot\Desktop\mapping_biller.xml
