server:
  port:
    8762

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  routes:
    serviceA:
      path: /def/**
      serviceId: WEB_SERVICE_WITH_EURAKA
    serviceB:
      path: /hij/**
      serviceId: WEB_SERVICE_WITH_EURAKA2
